---
login_url: account.hubstaff.com/login
username: your_username@yourmail.com
password: TheSuperSecuredPasswordHere9e9449584985
company_id: 19209
hours_a_day: 8
start_day: 27
end_day: 26
holidays:
  - '29.04.2019'
  - '30.04.2019'
vacations:
  - '10.05.2019'
day_offs:
  # - '10.05.2019'
